spring:
  data:
    mongodb:
      uri: mongodb+srv://collector-database:collector-database@collector-database.a6vvb30.mongodb.net/?retryWrites=true&w=majority&appName=Collector-database
      database: collector-database