spring:
  data:
    mongodb:
      uri: mongodb+srv://collector-database:collector-database@collector-database.a6vvb30.mongodb.net/?retryWrites=true&w=majority&appName=Collector-database
      database: collector-database

logging:
  pattern:
    console: "{\"time\": \"%d\", \"level\": \"%p\", \"correlation-id\": \"%X{X-Correlation-Id}\", \"source\": \"%logger{63}:%L\", \"message\": \"%replace(%m%wEx{6}){'[\r\n]+', '\\n'}%nopex\"}%n"